name = "server"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]


[dependencies]
gleam_stdlib = "~> 0.36.0"
common = {path = "../common"}
mist = "~> 0.17"
gleam_erlang = "~> 0.25"
gleam_http = "~> 3.6"
wisp = "~> 0.13"
lustre = ">= 4.2.2 and < 5.0.0"
gleam_json = "~> 1.0"
gleam_httpc = "~> 2.2"
snag = "~> 0.3"
verl = "~> 1.1"
dot_env = "~> 0.3"
sqlight = "~> 0.9"
gluid = "~> 1.0"
kirala_bbmarkdown = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
